using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ScienceMarketData;

public class City
{
    public int Id { get; set; }
    public int ProvinceId { get; set; }
    public string? Name { get; set; }



    public ICollection<Address> Addresses { get; set; } = new List<Address>();
    public Province? Province { get; set; }
}
public class CityConfiguration : IEntityTypeConfiguration<City>
{
    public void Configure(EntityTypeBuilder<City> builder)
    {
        builder.ToTable("Cities");
        builder.HasIndex(p => new { p.Name, p.ProvinceId }).IsUnique();
        builder.Property(p => p.Name).IsRequired();
        builder.HasMany(p => p.Addresses)
            .WithOne(p => p.City)
            .HasForeignKey(p => p.CityId)
            .OnDelete(DeleteBehavior.Restrict);

        builder
        .HasData(
            new City { Id = 1, ProvinceId = 37, Name = "ABANA" },
            new City { Id = 2, ProvinceId = 20, Name = "ACIPAYAM" },
            new City { Id = 3, ProvinceId = 34, Name = "ADALAR" },
            new City { Id = 4, ProvinceId = 1, Name = "SEYHAN" },
            new City { Id = 5, ProvinceId = 2, Name = "ADIYAMAN MERKEZ" },
            new City { Id = 6, ProvinceId = 13, Name = "ADİLCEVAZ" },
            new City { Id = 7, ProvinceId = 46, Name = "AFŞİN" },
            new City { Id = 8, ProvinceId = 3, Name = "AFYON MERKEZ" },
            new City { Id = 9, ProvinceId = 15, Name = "AĞLASUN" },
            new City { Id = 10, ProvinceId = 23, Name = "AĞIN" },
            new City { Id = 11, ProvinceId = 4, Name = "AĞRI MERKEZ" },
            new City { Id = 12, ProvinceId = 13, Name = "AHLAT" },
            new City { Id = 13, ProvinceId = 61, Name = "AKÇAABAT" },
            new City { Id = 14, ProvinceId = 44, Name = "AKÇADAĞ" },
            new City { Id = 15, ProvinceId = 63, Name = "AKÇAKALE" },
            new City { Id = 16, ProvinceId = 81, Name = "AKÇAKOCA" },
            new City { Id = 17, ProvinceId = 66, Name = "AKDAĞMADENİ" },
            new City { Id = 18, ProvinceId = 45, Name = "AKHİSAR" },
            new City { Id = 19, ProvinceId = 52, Name = "AKKUŞ" },
            new City { Id = 20, ProvinceId = 68, Name = "AKSARAY MERKEZ" },
            new City { Id = 21, ProvinceId = 7, Name = "AKSEKİ" },
            new City { Id = 22, ProvinceId = 42, Name = "AKŞEHİR" },
            new City { Id = 23, ProvinceId = 54, Name = "AKYAZI" },
            new City { Id = 24, ProvinceId = 19, Name = "ALACA" },
            new City { Id = 25, ProvinceId = 55, Name = "ALAÇAM" },
            new City { Id = 26, ProvinceId = 7, Name = "ALANYA" },
            new City { Id = 27, ProvinceId = 45, Name = "ALAŞEHİR" },
            new City { Id = 28, ProvinceId = 35, Name = "ALİAĞA" },
            new City { Id = 29, ProvinceId = 60, Name = "ALMUS" },
            new City { Id = 30, ProvinceId = 6, Name = "ALTINDAĞ" },
            new City { Id = 31, ProvinceId = 31, Name = "ALTINÖZÜ" },
            new City { Id = 32, ProvinceId = 43, Name = "ALTINTAŞ" },
            new City { Id = 33, ProvinceId = 28, Name = "ALUCRA" },
            new City { Id = 34, ProvinceId = 5, Name = "AMASYA MERKEZ" },
            new City { Id = 35, ProvinceId = 33, Name = "ANAMUR" },
            new City { Id = 36, ProvinceId = 46, Name = "ANDIRIN" },
            new City { Id = 37, ProvinceId = 6, Name = "ANKARA" },
            new City { Id = 38, ProvinceId = 7, Name = "ANTALYA MERKEZ" },
            new City { Id = 39, ProvinceId = 27, Name = "ARABAN" },
            new City { Id = 40, ProvinceId = 37, Name = "ARAÇ" },
            new City { Id = 41, ProvinceId = 61, Name = "ARAKLI" },
            new City { Id = 42, ProvinceId = 76, Name = "ARALIK" },
            new City { Id = 43, ProvinceId = 44, Name = "ARAPGİR" },
            new City { Id = 44, ProvinceId = 75, Name = "ARDAHAN MERKEZ" },
            new City { Id = 45, ProvinceId = 8, Name = "ARDANUÇ" },
            new City { Id = 46, ProvinceId = 53, Name = "ARDEŞEN" },
            new City { Id = 47, ProvinceId = 8, Name = "ARHAVİ" },
            new City { Id = 48, ProvinceId = 44, Name = "ARGUVAN" },
            new City { Id = 49, ProvinceId = 36, Name = "ARPAÇAY" },
            new City { Id = 50, ProvinceId = 61, Name = "ARSİN" },
            new City { Id = 51, ProvinceId = 60, Name = "ARTOVA" },
            new City { Id = 52, ProvinceId = 8, Name = "ARTVİN MERKEZ" },
            new City { Id = 53, ProvinceId = 25, Name = "AŞKALE" },
            new City { Id = 54, ProvinceId = 32, Name = "ATABEY" },
            new City { Id = 55, ProvinceId = 50, Name = "AVANOS" },
            new City { Id = 56, ProvinceId = 57, Name = "AYANCIK" },
            new City { Id = 57, ProvinceId = 6, Name = "AYAŞ" },
            new City { Id = 58, ProvinceId = 52, Name = "AYBASTI" },
            new City { Id = 59, ProvinceId = 9, Name = "AYDIN MERKEZ" },
            new City { Id = 60, ProvinceId = 17, Name = "AYVACIK" },
            new City { Id = 61, ProvinceId = 10, Name = "AYVALIK" },
            new City { Id = 62, ProvinceId = 37, Name = "AZDAVAY" },
            new City { Id = 63, ProvinceId = 39, Name = "BABAESKİ" },
            new City { Id = 64, ProvinceId = 55, Name = "BAFRA" },
            new City { Id = 65, ProvinceId = 80, Name = "BAHÇE" },
            new City { Id = 66, ProvinceId = 34, Name = "BAKIRKÖY" },
            new City { Id = 67, ProvinceId = 6, Name = "BALÂ" },
            new City { Id = 68, ProvinceId = 10, Name = "BALIKESİR MERKEZ" },
            new City { Id = 69, ProvinceId = 10, Name = "BALYA" },
            new City { Id = 70, ProvinceId = 64, Name = "BANAZ" },
            new City { Id = 71, ProvinceId = 10, Name = "BANDIRMA" },
            new City { Id = 72, ProvinceId = 74, Name = "BARTIN MERKEZ" },
            new City { Id = 73, ProvinceId = 23, Name = "BASKİL" },
            new City { Id = 74, ProvinceId = 72, Name = "BATMAN MERKEZ" },
            new City { Id = 75, ProvinceId = 65, Name = "BAŞKALE" },
            new City { Id = 76, ProvinceId = 69, Name = "BAYBURT MERKEZ" },
            new City { Id = 77, ProvinceId = 19, Name = "BAYAT" },
            new City { Id = 78, ProvinceId = 35, Name = "BAYINDIR" },
            new City { Id = 79, ProvinceId = 56, Name = "BAYKAN" },
            new City { Id = 80, ProvinceId = 17, Name = "BAYRAMİÇ" },
            new City { Id = 81, ProvinceId = 35, Name = "BERGAMA" },
            new City { Id = 82, ProvinceId = 2, Name = "BESNİ" },
            new City { Id = 83, ProvinceId = 34, Name = "BEŞİKTAŞ" },
            new City { Id = 84, ProvinceId = 72, Name = "BEŞİRİ" },
            new City { Id = 85, ProvinceId = 34, Name = "BEYKOZ" },
            new City { Id = 86, ProvinceId = 34, Name = "BEYOĞLU" },
            new City { Id = 87, ProvinceId = 6, Name = "BEYPAZARI" },
            new City { Id = 88, ProvinceId = 42, Name = "BEYŞEHİR" },
            new City { Id = 89, ProvinceId = 73, Name = "BEYTÜŞŞEBAP" },
            new City { Id = 90, ProvinceId = 17, Name = "BİGA" },
            new City { Id = 91, ProvinceId = 10, Name = "BİGADİÇ" },
            new City { Id = 92, ProvinceId = 11, Name = "BİLECİK MERKEZ" },
            new City { Id = 93, ProvinceId = 12, Name = "BİNGÖL MERKEZ" },
            new City { Id = 94, ProvinceId = 63, Name = "BİRECİK" },
            new City { Id = 95, ProvinceId = 21, Name = "BİSMİL" },
            new City { Id = 96, ProvinceId = 13, Name = "BİTLİS MERKEZ" },
            new City { Id = 97, ProvinceId = 48, Name = "BODRUM" },
            new City { Id = 98, ProvinceId = 66, Name = "BOĞAZLIYAN" },
            new City { Id = 99, ProvinceId = 14, Name = "BOLU MERKEZ" },
            new City { Id = 100, ProvinceId = 3, Name = "BOLVADİN" },
            new City { Id = 101, ProvinceId = 51, Name = "BOR" },
            new City { Id = 102, ProvinceId = 8, Name = "BORÇKA" },
            new City { Id = 103, ProvinceId = 35, Name = "BORNOVA" },
            new City { Id = 104, ProvinceId = 57, Name = "BOYABAT" },
            new City { Id = 105, ProvinceId = 17, Name = "BOZCAADA" },
            new City { Id = 106, ProvinceId = 9, Name = "BOZDOĞAN" },
            new City { Id = 107, ProvinceId = 42, Name = "BOZKIR" },
            new City { Id = 108, ProvinceId = 37, Name = "BOZKURT" },
            new City { Id = 109, ProvinceId = 63, Name = "BOZOVA" },
            new City { Id = 110, ProvinceId = 11, Name = "BOZÜYÜK" },
            new City { Id = 111, ProvinceId = 15, Name = "BUCAK" },
            new City { Id = 112, ProvinceId = 28, Name = "BULANCAK" },
            new City { Id = 113, ProvinceId = 49, Name = "BULANIK" },
            new City { Id = 114, ProvinceId = 20, Name = "BULDAN" },
            new City { Id = 115, ProvinceId = 15, Name = "BURDUR MERKEZ" },
            new City { Id = 116, ProvinceId = 10, Name = "BURHANİYE" },
            new City { Id = 117, ProvinceId = 16, Name = "BURSA MERKEZ" },
            new City { Id = 118, ProvinceId = 38, Name = "BÜNYAN" },
            new City { Id = 119, ProvinceId = 1, Name = "CEYHAN" },
            new City { Id = 120, ProvinceId = 63, Name = "CEYLANPINAR" },
            new City { Id = 121, ProvinceId = 37, Name = "CİDE" },
            new City { Id = 122, ProvinceId = 42, Name = "CİHANBEYLİ" },
            new City { Id = 123, ProvinceId = 73, Name = "CİZRE" },
            new City { Id = 124, ProvinceId = 20, Name = "ÇAL" },
            new City { Id = 125, ProvinceId = 51, Name = "ÇAMARDI" },
            new City { Id = 126, ProvinceId = 20, Name = "ÇAMELİ" },
            new City { Id = 127, ProvinceId = 6, Name = "ÇAMLIDERE" },
            new City { Id = 128, ProvinceId = 53, Name = "ÇAMLIHEMŞİN" },
            new City { Id = 129, ProvinceId = 17, Name = "ÇAN" },
            new City { Id = 130, ProvinceId = 17, Name = "ÇANAKKALE MERKEZ" },
            new City { Id = 131, ProvinceId = 6, Name = "ÇANKAYA" },
            new City { Id = 132, ProvinceId = 18, Name = "ÇANKIRI MERKEZ" },
            new City { Id = 133, ProvinceId = 20, Name = "ÇARDAK" },
            new City { Id = 134, ProvinceId = 55, Name = "ÇARŞAMBA" },
            new City { Id = 135, ProvinceId = 25, Name = "ÇAT" },
            new City { Id = 136, ProvinceId = 65, Name = "ÇATAK" },
            new City { Id = 137, ProvinceId = 34, Name = "ÇATALCA" },
            new City { Id = 138, ProvinceId = 37, Name = "ÇATALZEYTİN" },
            new City { Id = 139, ProvinceId = 3, Name = "ÇAY" },
            new City { Id = 140, ProvinceId = 67, Name = "ÇAYCUMA" },
            new City { Id = 141, ProvinceId = 53, Name = "ÇAYELİ" },
            new City { Id = 142, ProvinceId = 66, Name = "ÇAYIRALAN" },
            new City { Id = 143, ProvinceId = 24, Name = "ÇAYIRLI" },
            new City { Id = 144, ProvinceId = 61, Name = "ÇAYKARA" },
            new City { Id = 145, ProvinceId = 66, Name = "ÇEKEREK" },
            new City { Id = 146, ProvinceId = 2, Name = "ÇELİKHAN" },
            new City { Id = 147, ProvinceId = 62, Name = "ÇEMİŞGEZEK" },
            new City { Id = 148, ProvinceId = 18, Name = "ÇERKEŞ" },
            new City { Id = 149, ProvinceId = 21, Name = "ÇERMİK" },
            new City { Id = 150, ProvinceId = 59, Name = "ÇERKEZKÖY" },
            new City { Id = 151, ProvinceId = 35, Name = "ÇEŞME" },
            new City { Id = 152, ProvinceId = 75, Name = "ÇILDIR" },
            new City { Id = 153, ProvinceId = 21, Name = "ÇINAR" },
            new City { Id = 154, ProvinceId = 40, Name = "ÇİÇEKDAĞI" },
            new City { Id = 155, ProvinceId = 26, Name = "ÇİFTELER" },
            new City { Id = 156, ProvinceId = 9, Name = "ÇİNE" },
            new City { Id = 157, ProvinceId = 20, Name = "ÇİVRİL" },
            new City { Id = 158, ProvinceId = 59, Name = "ÇORLU" },
            new City { Id = 159, ProvinceId = 19, Name = "ÇORUM MERKEZ" },
            new City { Id = 160, ProvinceId = 6, Name = "ÇUBUK" },
            new City { Id = 161, ProvinceId = 30, Name = "ÇUKURCA" },
            new City { Id = 162, ProvinceId = 42, Name = "ÇUMRA" },
            new City { Id = 163, ProvinceId = 21, Name = "ÇÜNGÜŞ" },
            new City { Id = 164, ProvinceId = 37, Name = "DADAY" },
            new City { Id = 165, ProvinceId = 44, Name = "DARENDE" },
            new City { Id = 166, ProvinceId = 48, Name = "DATÇA" },
            new City { Id = 167, ProvinceId = 3, Name = "DAZKIRI" },
            new City { Id = 168, ProvinceId = 71, Name = "DELİCE" },
            new City { Id = 169, ProvinceId = 45, Name = "DEMİRCİ" },
            new City { Id = 170, ProvinceId = 39, Name = "DEMİRKÖY" },
            new City { Id = 171, ProvinceId = 20, Name = "DENİZLİ MERKEZ" },
            new City { Id = 172, ProvinceId = 28, Name = "DERELİ" },
            new City { Id = 173, ProvinceId = 47, Name = "DERİK" },
            new City { Id = 174, ProvinceId = 50, Name = "DERİNKUYU" },
            new City { Id = 175, ProvinceId = 38, Name = "DEVELİ" },
            new City { Id = 176, ProvinceId = 67, Name = "DEVREK" },
            new City { Id = 177, ProvinceId = 37, Name = "DEVREKÂNİ" },
            new City { Id = 178, ProvinceId = 21, Name = "DİCLE" },
            new City { Id = 179, ProvinceId = 36, Name = "DİGOR" },
            new City { Id = 180, ProvinceId = 35, Name = "DİKİLİ" },
            new City { Id = 181, ProvinceId = 3, Name = "DİNAR" },
            new City { Id = 182, ProvinceId = 58, Name = "DİVRİĞİ" },
            new City { Id = 183, ProvinceId = 4, Name = "DİYADİN" },
            new City { Id = 184, ProvinceId = 21, Name = "DİYARBAKIR MERKEZ" },
            new City { Id = 185, ProvinceId = 42, Name = "DOĞANHİSAR" },
            new City { Id = 186, ProvinceId = 44, Name = "DOĞANŞEHİR" },
            new City { Id = 187, ProvinceId = 4, Name = "DOĞUBAYAZIT" },
            new City { Id = 188, ProvinceId = 43, Name = "DOMANİÇ" },
            new City { Id = 189, ProvinceId = 31, Name = "DÖRTYOL" },
            new City { Id = 190, ProvinceId = 57, Name = "DURAĞAN" },
            new City { Id = 191, ProvinceId = 10, Name = "DURSUNBEY" },
            new City { Id = 192, ProvinceId = 81, Name = "DÜZCE MERKEZ" },
            new City { Id = 193, ProvinceId = 17, Name = "ECEABAT" },
            new City { Id = 194, ProvinceId = 10, Name = "EDREMİT" },
            new City { Id = 195, ProvinceId = 22, Name = "EDİRNE MERKEZ" },
            new City { Id = 196, ProvinceId = 78, Name = "EFLÂNİ" },
            new City { Id = 197, ProvinceId = 32, Name = "EĞİRDİR" },
            new City { Id = 198, ProvinceId = 23, Name = "ELAZIĞ MERKEZ" },
            new City { Id = 199, ProvinceId = 46, Name = "ELBİSTAN" },
            new City { Id = 200, ProvinceId = 18, Name = "ELDİVAN" },
            new City { Id = 201, ProvinceId = 4, Name = "ELEŞKİRT" },
            new City { Id = 202, ProvinceId = 6, Name = "ELMADAĞ" },
            new City { Id = 203, ProvinceId = 7, Name = "ELMALI" },
            new City { Id = 204, ProvinceId = 43, Name = "EMET" },
            new City { Id = 205, ProvinceId = 34, Name = "EMİNÖNÜ" },
            new City { Id = 206, ProvinceId = 3, Name = "EMİRDAĞ" },
            new City { Id = 207, ProvinceId = 22, Name = "ENEZ" },
            new City { Id = 208, ProvinceId = 60, Name = "ERBAA" },
            new City { Id = 209, ProvinceId = 65, Name = "ERCİŞ" },
            new City { Id = 210, ProvinceId = 10, Name = "ERDEK" },
            new City { Id = 211, ProvinceId = 33, Name = "ERDEMLİ" },
            new City { Id = 212, ProvinceId = 42, Name = "EREĞLİ" },
            new City { Id = 213, ProvinceId = 67, Name = "EREĞLİ" },
            new City { Id = 214, ProvinceId = 57, Name = "ERFELEK" },
            new City { Id = 215, ProvinceId = 21, Name = "ERGANİ" },
            new City { Id = 216, ProvinceId = 70, Name = "ERMENEK" },
            new City { Id = 217, ProvinceId = 56, Name = "ERUH" },
            new City { Id = 218, ProvinceId = 24, Name = "ERZİNCAN MERKEZ" },
            new City { Id = 219, ProvinceId = 25, Name = "ERZURUM MERKEZ" },
            new City { Id = 220, ProvinceId = 28, Name = "ESPİYE" },
            new City { Id = 221, ProvinceId = 78, Name = "ESKİPAZAR" },
            new City { Id = 222, ProvinceId = 26, Name = "ESKİŞEHİR MERKEZ" },
            new City { Id = 223, ProvinceId = 64, Name = "EŞME" },
            new City { Id = 224, ProvinceId = 28, Name = "EYNESİL" },
            new City { Id = 225, ProvinceId = 34, Name = "EYÜP" },
            new City { Id = 226, ProvinceId = 17, Name = "EZİNE" },
            new City { Id = 227, ProvinceId = 34, Name = "FATİH" },
            new City { Id = 228, ProvinceId = 52, Name = "FATSA" },
            new City { Id = 229, ProvinceId = 1, Name = "FEKE" },
            new City { Id = 230, ProvinceId = 38, Name = "FELAHİYE" },
            new City { Id = 231, ProvinceId = 48, Name = "FETHİYE" },
            new City { Id = 232, ProvinceId = 53, Name = "FINDIKLI" },
            new City { Id = 233, ProvinceId = 7, Name = "FİNİKE" },
            new City { Id = 234, ProvinceId = 35, Name = "FOÇA" },
            new City { Id = 235, ProvinceId = 27, Name = "GAZİANTEP MERKEZ" },
            new City { Id = 236, ProvinceId = 34, Name = "GAZİOSMANPAŞA" },
            new City { Id = 237, ProvinceId = 7, Name = "GAZİPAŞA" },
            new City { Id = 238, ProvinceId = 41, Name = "GEBZE" },
            new City { Id = 239, ProvinceId = 43, Name = "GEDİZ" },
            new City { Id = 240, ProvinceId = 17, Name = "GELİBOLU" },
            new City { Id = 241, ProvinceId = 32, Name = "GELENDOST" },
            new City { Id = 242, ProvinceId = 58, Name = "GEMEREK" },
            new City { Id = 243, ProvinceId = 16, Name = "GEMLİK" },
            new City { Id = 244, ProvinceId = 12, Name = "GENÇ" },
            new City { Id = 245, ProvinceId = 72, Name = "GERCÜŞ" },
            new City { Id = 246, ProvinceId = 14, Name = "GEREDE" },
            new City { Id = 247, ProvinceId = 2, Name = "GERGER" },
            new City { Id = 248, ProvinceId = 9, Name = "GERMENCİK" },
            new City { Id = 249, ProvinceId = 57, Name = "GERZE" },
            new City { Id = 250, ProvinceId = 65, Name = "GEVAŞ" },
            new City { Id = 251, ProvinceId = 54, Name = "GEYVE" },
            new City { Id = 252, ProvinceId = 28, Name = "GİRESUN MERKEZ" },
            new City { Id = 253, ProvinceId = 46, Name = "GÖKSUN" },
            new City { Id = 254, ProvinceId = 2, Name = "GÖLBAŞI" },
            new City { Id = 255, ProvinceId = 41, Name = "GÖLCÜK" },
            new City { Id = 256, ProvinceId = 75, Name = "GÖLE" },
            new City { Id = 257, ProvinceId = 15, Name = "GÖLHİSAR" },
            new City { Id = 258, ProvinceId = 52, Name = "GÖLKÖY" },
            new City { Id = 259, ProvinceId = 11, Name = "GÖLPAZARI" },
            new City { Id = 260, ProvinceId = 10, Name = "GÖNEN" },
            new City { Id = 261, ProvinceId = 28, Name = "GÖRELE" },
            new City { Id = 262, ProvinceId = 45, Name = "GÖRDES" },
            new City { Id = 263, ProvinceId = 5, Name = "GÖYNÜCEK" },
            new City { Id = 264, ProvinceId = 14, Name = "GÖYNÜK" },
            new City { Id = 265, ProvinceId = 6, Name = "GÜDÜL" },
            new City { Id = 266, ProvinceId = 33, Name = "GÜLNAR" },
            new City { Id = 267, ProvinceId = 50, Name = "GÜLŞEHİR" },
            new City { Id = 268, ProvinceId = 5, Name = "GÜMÜŞHACIKÖY" },
            new City { Id = 269, ProvinceId = 29, Name = "GÜMÜŞHANE MERKEZ" },
            new City { Id = 270, ProvinceId = 7, Name = "GÜNDOĞMUŞ" },
            new City { Id = 271, ProvinceId = 20, Name = "GÜNEY" },
            new City { Id = 272, ProvinceId = 65, Name = "GÜRPINAR" },
            new City { Id = 273, ProvinceId = 58, Name = "GÜRÜN" },
            new City { Id = 274, ProvinceId = 50, Name = "HACIBEKTAŞ" },
            new City { Id = 275, ProvinceId = 42, Name = "HADIM" },
            new City { Id = 276, ProvinceId = 58, Name = "HAFİK" },
            new City { Id = 277, ProvinceId = 30, Name = "HAKKARİ MERKEZ" },
            new City { Id = 278, ProvinceId = 63, Name = "HALFETİ" },
            new City { Id = 279, ProvinceId = 4, Name = "HAMUR" },
            new City { Id = 280, ProvinceId = 75, Name = "HANAK" },
            new City { Id = 281, ProvinceId = 21, Name = "HANİ" },
            new City { Id = 282, ProvinceId = 31, Name = "HASSA" },
            new City { Id = 283, ProvinceId = 31, Name = "HATAY MERKEZ" },
            new City { Id = 284, ProvinceId = 10, Name = "HAVRAN" },
            new City { Id = 285, ProvinceId = 22, Name = "HAVSA" },
            new City { Id = 286, ProvinceId = 55, Name = "HAVZA" },
            new City { Id = 287, ProvinceId = 6, Name = "HAYMANA" },
            new City { Id = 288, ProvinceId = 59, Name = "HAYRABOLU" },
            new City { Id = 289, ProvinceId = 21, Name = "HAZRO" },
            new City { Id = 290, ProvinceId = 44, Name = "HEKİMHAN" },
            new City { Id = 291, ProvinceId = 54, Name = "HENDEK" },
            new City { Id = 292, ProvinceId = 25, Name = "HINIS" },
            new City { Id = 293, ProvinceId = 63, Name = "HİLVAN" },
            new City { Id = 294, ProvinceId = 13, Name = "HİZAN" },
            new City { Id = 295, ProvinceId = 8, Name = "HOPA" },
            new City { Id = 296, ProvinceId = 25, Name = "HORASAN" },
            new City { Id = 297, ProvinceId = 62, Name = "HOZAT" },
            new City { Id = 298, ProvinceId = 76, Name = "IĞDIR MERKEZ" },
            new City { Id = 299, ProvinceId = 18, Name = "ILGAZ" },
            new City { Id = 300, ProvinceId = 42, Name = "ILGIN" },
            new City { Id = 301, ProvinceId = 32, Name = "ISPARTA MERKEZ" },
            new City { Id = 302, ProvinceId = 33, Name = "İÇEL MERKEZ" },
            new City { Id = 303, ProvinceId = 73, Name = "İDİL" },
            new City { Id = 304, ProvinceId = 3, Name = "İHSANİYE" },
            new City { Id = 305, ProvinceId = 53, Name = "İKİZDERE" },
            new City { Id = 306, ProvinceId = 24, Name = "İLİÇ" },
            new City { Id = 307, ProvinceId = 58, Name = "İMRANLI" },
            new City { Id = 308, ProvinceId = 17, Name = "GÖKÇEADA (İMROZ)" },
            new City { Id = 309, ProvinceId = 38, Name = "İNCESU" },
            new City { Id = 310, ProvinceId = 37, Name = "İNEBOLU" },
            new City { Id = 311, ProvinceId = 16, Name = "İNEGÖL" },
            new City { Id = 312, ProvinceId = 22, Name = "İPSALA" },
            new City { Id = 313, ProvinceId = 31, Name = "İSKENDERUN" },
            new City { Id = 314, ProvinceId = 19, Name = "İSKİLİP" },
            new City { Id = 315, ProvinceId = 27, Name = "İSLAHİYE" },
            new City { Id = 316, ProvinceId = 25, Name = "İSPİR" },
            new City { Id = 317, ProvinceId = 34, Name = "İSTANBUL MERKEZ" },
            new City { Id = 318, ProvinceId = 10, Name = "İVRİNDİ" },
            new City { Id = 319, ProvinceId = 35, Name = "İZMİR MERKEZ" },
            new City { Id = 320, ProvinceId = 16, Name = "İZNİK" },
            new City { Id = 321, ProvinceId = 34, Name = "KADIKÖY" },
            new City { Id = 322, ProvinceId = 42, Name = "KADINHANI" },
            new City { Id = 323, ProvinceId = 80, Name = "KADİRLİ" },
            new City { Id = 324, ProvinceId = 36, Name = "KAĞIZMAN" },
            new City { Id = 325, ProvinceId = 2, Name = "KAHTA" },
            new City { Id = 326, ProvinceId = 20, Name = "KALE" },
            new City { Id = 327, ProvinceId = 6, Name = "KALECİK" },
            new City { Id = 328, ProvinceId = 53, Name = "KALKANDERE" },
            new City { Id = 329, ProvinceId = 40, Name = "KAMAN" },
            new City { Id = 330, ProvinceId = 41, Name = "KANDIRA" },
            new City { Id = 331, ProvinceId = 58, Name = "KANGAL" },
            new City { Id = 332, ProvinceId = 35, Name = "KARABURUN" },
            new City { Id = 333, ProvinceId = 78, Name = "KARABÜK MERKEZ" },
            new City { Id = 334, ProvinceId = 16, Name = "KARACABEY" },
            new City { Id = 335, ProvinceId = 9, Name = "KARACASU" },
            new City { Id = 336, ProvinceId = 64, Name = "KARAHALLI" },
            new City { Id = 337, ProvinceId = 1, Name = "KARAİSALI" },
            new City { Id = 338, ProvinceId = 23, Name = "KARAKOÇAN" },
            new City { Id = 339, ProvinceId = 70, Name = "KARAMAN MERKEZ" },
            new City { Id = 340, ProvinceId = 41, Name = "KARAMÜRSEL" },
            new City { Id = 341, ProvinceId = 42, Name = "KARAPINAR" },
            new City { Id = 342, ProvinceId = 54, Name = "KARASU" },
            new City { Id = 343, ProvinceId = 1, Name = "KARATAŞ" },
            new City { Id = 344, ProvinceId = 25, Name = "KARAYAZI" },
            new City { Id = 345, ProvinceId = 19, Name = "KARGI" },
            new City { Id = 346, ProvinceId = 12, Name = "KARLIOVA" },
            new City { Id = 347, ProvinceId = 36, Name = "KARS MERKEZ" },
            new City { Id = 348, ProvinceId = 35, Name = "KARŞIYAKA" },
            new City { Id = 349, ProvinceId = 34, Name = "KARTAL" },
            new City { Id = 350, ProvinceId = 37, Name = "KASTAMONU MERKEZ" },
            new City { Id = 351, ProvinceId = 7, Name = "KAŞ" },
            new City { Id = 352, ProvinceId = 55, Name = "KAVAK" },
            new City { Id = 353, ProvinceId = 54, Name = "KAYNARCA" },
            new City { Id = 354, ProvinceId = 38, Name = "KAYSERİ MERKEZ" },
            new City { Id = 355, ProvinceId = 23, Name = "KEBAN" },
            new City { Id = 356, ProvinceId = 32, Name = "KEÇİBORLU" },
            new City { Id = 357, ProvinceId = 16, Name = "KELES" },
            new City { Id = 358, ProvinceId = 29, Name = "KELKİT" },
            new City { Id = 359, ProvinceId = 24, Name = "KEMAH" },
            new City { Id = 360, ProvinceId = 24, Name = "KEMALİYE" },
            new City { Id = 361, ProvinceId = 35, Name = "KEMALPAŞA" },
            new City { Id = 362, ProvinceId = 10, Name = "KEPSUT" },
            new City { Id = 363, ProvinceId = 71, Name = "KESKİN" },
            new City { Id = 364, ProvinceId = 22, Name = "KEŞAN" },
            new City { Id = 365, ProvinceId = 28, Name = "KEŞAP" },
            new City { Id = 366, ProvinceId = 14, Name = "KIBRISCIK" },
            new City { Id = 367, ProvinceId = 35, Name = "KINIK" },
            new City { Id = 368, ProvinceId = 31, Name = "KIRIKHAN" },
            new City { Id = 369, ProvinceId = 71, Name = "KIRIKKALE MERKEZ" },
            new City { Id = 370, ProvinceId = 45, Name = "KIRKAĞAÇ" },
            new City { Id = 371, ProvinceId = 39, Name = "KIRKLARELİ MERKEZ" },
            new City { Id = 372, ProvinceId = 40, Name = "KIRŞEHİR MERKEZ" },
            new City { Id = 373, ProvinceId = 6, Name = "KIZILCAHAMAM" },
            new City { Id = 374, ProvinceId = 47, Name = "KIZILTEPE" },
            new City { Id = 375, ProvinceId = 12, Name = "KİĞI" },
            new City { Id = 376, ProvinceId = 79, Name = "KİLİS MERKEZ" },
            new City { Id = 377, ProvinceId = 35, Name = "KİRAZ" },
            new City { Id = 378, ProvinceId = 41, Name = "KOCAELİ MERKEZ (İZMİT)" },
            new City { Id = 379, ProvinceId = 9, Name = "KOÇARLI" },
            new City { Id = 380, ProvinceId = 39, Name = "KOFÇAZ" },
            new City { Id = 381, ProvinceId = 42, Name = "KONYA MERKEZ" },
            new City { Id = 382, ProvinceId = 52, Name = "KORGAN" },
            new City { Id = 383, ProvinceId = 7, Name = "KORKUTELİ" },
            new City { Id = 384, ProvinceId = 58, Name = "KOYULHİSAR" },
            new City { Id = 385, ProvinceId = 50, Name = "KOZAKLI" },
            new City { Id = 386, ProvinceId = 1, Name = "KOZAN" },
            new City { Id = 387, ProvinceId = 72, Name = "KOZLUK" },
            new City { Id = 388, ProvinceId = 48, Name = "KÖYCEĞİZ" },
            new City { Id = 389, ProvinceId = 45, Name = "KULA" },
            new City { Id = 390, ProvinceId = 21, Name = "KULP" },
            new City { Id = 391, ProvinceId = 42, Name = "KULU" },
            new City { Id = 392, ProvinceId = 7, Name = "KUMLUCA" },
            new City { Id = 393, ProvinceId = 52, Name = "KUMRU" },
            new City { Id = 394, ProvinceId = 18, Name = "KURŞUNLU" },
            new City { Id = 395, ProvinceId = 56, Name = "KURTALAN" },
            new City { Id = 396, ProvinceId = 74, Name = "KURUCAŞİLE" },
            new City { Id = 397, ProvinceId = 9, Name = "KUŞADASI" },
            new City { Id = 398, ProvinceId = 9, Name = "KUYUCAK" },
            new City { Id = 399, ProvinceId = 37, Name = "KÜRE" },
            new City { Id = 400, ProvinceId = 43, Name = "KÜTAHYA MERKEZ" },
            new City { Id = 401, ProvinceId = 55, Name = "LADİK" },
            new City { Id = 402, ProvinceId = 22, Name = "LALAPAŞA" },
            new City { Id = 403, ProvinceId = 17, Name = "LAPSEKİ" },
            new City { Id = 404, ProvinceId = 21, Name = "LİCE" },
            new City { Id = 405, ProvinceId = 39, Name = "LÜLEBURGAZ" },
            new City { Id = 406, ProvinceId = 23, Name = "MADEN" },
            new City { Id = 407, ProvinceId = 61, Name = "MAÇKA" },
            new City { Id = 408, ProvinceId = 26, Name = "MAHMUDİYE" },
            new City { Id = 409, ProvinceId = 44, Name = "MALATYA MERKEZ" },
            new City { Id = 410, ProvinceId = 49, Name = "MALAZGİRT" },
            new City { Id = 411, ProvinceId = 59, Name = "MALKARA" },
            new City { Id = 412, ProvinceId = 7, Name = "MANAVGAT" },
            new City { Id = 413, ProvinceId = 45, Name = "MANİSA MERKEZ" },
            new City { Id = 414, ProvinceId = 10, Name = "MANYAS" },
            new City { Id = 415, ProvinceId = 46, Name = "KAHRAMANMARAŞ MERKEZ" },
            new City { Id = 416, ProvinceId = 47, Name = "MARDİN MERKEZ" },
            new City { Id = 417, ProvinceId = 48, Name = "MARMARİS" },
            new City { Id = 418, ProvinceId = 62, Name = "MAZGİRT" },
            new City { Id = 419, ProvinceId = 47, Name = "MAZIDAĞI" },
            new City { Id = 420, ProvinceId = 19, Name = "MECİTÖZÜ" },
            new City { Id = 421, ProvinceId = 35, Name = "MENEMEN" },
            new City { Id = 422, ProvinceId = 14, Name = "MENGEN" },
            new City { Id = 423, ProvinceId = 22, Name = "MERİÇ" },
            new City { Id = 424, ProvinceId = 5, Name = "MERZİFON" },
            new City { Id = 425, ProvinceId = 52, Name = "MESUDİYE" },
            new City { Id = 426, ProvinceId = 47, Name = "MİDYAT" },
            new City { Id = 427, ProvinceId = 26, Name = "MİHALIÇÇIK" },
            new City { Id = 428, ProvinceId = 48, Name = "MİLAS" },
            new City { Id = 429, ProvinceId = 40, Name = "MUCUR" },
            new City { Id = 430, ProvinceId = 16, Name = "MUDANYA" },
            new City { Id = 431, ProvinceId = 14, Name = "MUDURNU" },
            new City { Id = 432, ProvinceId = 48, Name = "MUĞLA MERKEZ" },
            new City { Id = 433, ProvinceId = 65, Name = "MURADİYE" },
            new City { Id = 434, ProvinceId = 49, Name = "MUŞ MERKEZ" },
            new City { Id = 435, ProvinceId = 16, Name = "MUSTAFA KEMAL PAŞA" },
            new City { Id = 436, ProvinceId = 33, Name = "MUT" },
            new City { Id = 437, ProvinceId = 13, Name = "MUTKİ" },
            new City { Id = 438, ProvinceId = 59, Name = "MURATLI" },
            new City { Id = 439, ProvinceId = 6, Name = "NALLIHAN" },
            new City { Id = 440, ProvinceId = 25, Name = "NARMAN" },
            new City { Id = 441, ProvinceId = 62, Name = "NAZIMİYE" },
            new City { Id = 442, ProvinceId = 9, Name = "NAZİLLİ" },
            new City { Id = 443, ProvinceId = 50, Name = "NEVŞEHİR MERKEZ" },
            new City { Id = 444, ProvinceId = 51, Name = "NİĞDE MERKEZ" },
            new City { Id = 445, ProvinceId = 60, Name = "NİKSAR" },
            new City { Id = 446, ProvinceId = 27, Name = "NİZİP" },
            new City { Id = 447, ProvinceId = 47, Name = "NUSAYBİN" },
            new City { Id = 448, ProvinceId = 61, Name = "OF" },
            new City { Id = 449, ProvinceId = 27, Name = "OĞUZELİ" },
            new City { Id = 450, ProvinceId = 25, Name = "OLTU" },
            new City { Id = 451, ProvinceId = 25, Name = "OLUR" },
            new City { Id = 452, ProvinceId = 52, Name = "ORDU MERKEZ" },
            new City { Id = 453, ProvinceId = 16, Name = "ORHANELİ" },
            new City { Id = 454, ProvinceId = 16, Name = "ORHANGAZİ" },
            new City { Id = 455, ProvinceId = 18, Name = "ORTA" },
            new City { Id = 456, ProvinceId = 19, Name = "ORTAKÖY" },
            new City { Id = 457, ProvinceId = 68, Name = "ORTAKÖY" },
            new City { Id = 458, ProvinceId = 19, Name = "OSMANCIK" },
            new City { Id = 459, ProvinceId = 11, Name = "OSMANELİ" },
            new City { Id = 460, ProvinceId = 80, Name = "OSMANİYE MERKEZ" },
            new City { Id = 461, ProvinceId = 78, Name = "OVACIK" },
            new City { Id = 462, ProvinceId = 62, Name = "OVACIK" },
            new City { Id = 463, ProvinceId = 35, Name = "ÖDEMİŞ" },
            new City { Id = 464, ProvinceId = 47, Name = "ÖMERLİ" },
            new City { Id = 465, ProvinceId = 65, Name = "ÖZALP" },
            new City { Id = 466, ProvinceId = 23, Name = "PALU" },
            new City { Id = 467, ProvinceId = 25, Name = "PASİNLER" },
            new City { Id = 468, ProvinceId = 4, Name = "PATNOS" },
            new City { Id = 469, ProvinceId = 53, Name = "PAZAR" },
            new City { Id = 470, ProvinceId = 46, Name = "PAZARCIK" },
            new City { Id = 471, ProvinceId = 11, Name = "PAZARYERİ" },
            new City { Id = 472, ProvinceId = 39, Name = "PEHLİVANKÖY" },
            new City { Id = 473, ProvinceId = 52, Name = "PERŞEMBE" },
            new City { Id = 474, ProvinceId = 62, Name = "PERTEK" },
            new City { Id = 475, ProvinceId = 56, Name = "PERVARİ" },
            new City { Id = 476, ProvinceId = 38, Name = "PINARBAŞI" },
            new City { Id = 477, ProvinceId = 39, Name = "PINARHİSAR" },
            new City { Id = 478, ProvinceId = 6, Name = "POLATLI" },
            new City { Id = 479, ProvinceId = 75, Name = "POSOF" },
            new City { Id = 480, ProvinceId = 1, Name = "POZANTI" },
            new City { Id = 481, ProvinceId = 62, Name = "PÜLÜMÜR" },
            new City { Id = 482, ProvinceId = 44, Name = "PÜTÜRGE" },
            new City { Id = 483, ProvinceId = 24, Name = "REFAHİYE" },
            new City { Id = 484, ProvinceId = 60, Name = "REŞADİYE" },
            new City { Id = 485, ProvinceId = 31, Name = "REYHANLI" },
            new City { Id = 486, ProvinceId = 53, Name = "RİZE MERKEZ" },
            new City { Id = 487, ProvinceId = 78, Name = "SAFRANBOLU" },
            new City { Id = 488, ProvinceId = 1, Name = "SAİMBEYLİ" },
            new City { Id = 489, ProvinceId = 54, Name = "SAKARYA MERKEZ (ADAPAZARI)" },
            new City { Id = 490, ProvinceId = 45, Name = "SALİHLİ" },
            new City { Id = 491, ProvinceId = 31, Name = "SAMANDAĞ" },
            new City { Id = 492, ProvinceId = 2, Name = "SAMSAT" },
            new City { Id = 493, ProvinceId = 55, Name = "SAMSUN MERKEZ" },
            new City { Id = 494, ProvinceId = 3, Name = "SANDIKLI" },
            new City { Id = 495, ProvinceId = 54, Name = "SAPANCA" },
            new City { Id = 496, ProvinceId = 59, Name = "SARAY" },
            new City { Id = 497, ProvinceId = 20, Name = "SARAYKÖY" },
            new City { Id = 498, ProvinceId = 42, Name = "SARAYÖNÜ" },
            new City { Id = 499, ProvinceId = 26, Name = "SARICAKAYA" },
            new City { Id = 500, ProvinceId = 45, Name = "SARIGÖL" },
            new City { Id = 501, ProvinceId = 36, Name = "SARIKAMIŞ" },
            new City { Id = 502, ProvinceId = 66, Name = "SARIKAYA" },
            new City { Id = 503, ProvinceId = 38, Name = "SARIOĞLAN" },
            new City { Id = 504, ProvinceId = 34, Name = "SARIYER" },
            new City { Id = 505, ProvinceId = 38, Name = "SARIZ" },
            new City { Id = 506, ProvinceId = 45, Name = "SARUHANLI" },
            new City { Id = 507, ProvinceId = 72, Name = "SASON" },
            new City { Id = 508, ProvinceId = 10, Name = "SAVAŞTEPE" },
            new City { Id = 509, ProvinceId = 47, Name = "SAVUR" },
            new City { Id = 510, ProvinceId = 14, Name = "SEBEN" },
            new City { Id = 511, ProvinceId = 35, Name = "SEFERİHİSAR" },
            new City { Id = 512, ProvinceId = 35, Name = "SELÇUK" },
            new City { Id = 513, ProvinceId = 45, Name = "SELENDİ" },
            new City { Id = 514, ProvinceId = 36, Name = "SELİM" },
            new City { Id = 515, ProvinceId = 32, Name = "SENİRKENT" },
            new City { Id = 516, ProvinceId = 7, Name = "SERİK" },
            new City { Id = 517, ProvinceId = 42, Name = "SEYDİŞEHİR" },
            new City { Id = 518, ProvinceId = 26, Name = "SEYİTGAZİ" },
            new City { Id = 519, ProvinceId = 10, Name = "SINDIRGI" },
            new City { Id = 520, ProvinceId = 56, Name = "SİİRT MERKEZ" },
            new City { Id = 521, ProvinceId = 33, Name = "SİLİFKE" },
            new City { Id = 522, ProvinceId = 34, Name = "SİLİVRİ" },
            new City { Id = 523, ProvinceId = 73, Name = "SİLOPİ" },
            new City { Id = 524, ProvinceId = 21, Name = "SİLVAN" },
            new City { Id = 525, ProvinceId = 43, Name = "SİMAV" },
            new City { Id = 526, ProvinceId = 3, Name = "SİNCANLI" },
            new City { Id = 527, ProvinceId = 57, Name = "SİNOP MERKEZ" },
            new City { Id = 528, ProvinceId = 58, Name = "SİVAS MERKEZ" },
            new City { Id = 529, ProvinceId = 64, Name = "SİVASLI" },
            new City { Id = 530, ProvinceId = 63, Name = "SİVEREK" },
            new City { Id = 531, ProvinceId = 23, Name = "SİVRİCE" },
            new City { Id = 532, ProvinceId = 26, Name = "SİVRİHİSAR" },
            new City { Id = 533, ProvinceId = 12, Name = "SOLHAN" },
            new City { Id = 534, ProvinceId = 45, Name = "SOMA" },
            new City { Id = 535, ProvinceId = 66, Name = "SORGUN" },
            new City { Id = 536, ProvinceId = 11, Name = "SÖĞÜT" },
            new City { Id = 537, ProvinceId = 9, Name = "SÖKE" },
            new City { Id = 538, ProvinceId = 71, Name = "SULAKYURT" },
            new City { Id = 539, ProvinceId = 3, Name = "SULTANDAĞI" },
            new City { Id = 540, ProvinceId = 9, Name = "SULTANHİSAR" },
            new City { Id = 541, ProvinceId = 5, Name = "SULUOVA" },
            new City { Id = 542, ProvinceId = 19, Name = "SUNGURLU" },
            new City { Id = 543, ProvinceId = 63, Name = "SURUÇ" },
            new City { Id = 544, ProvinceId = 10, Name = "SUSURLUK" },
            new City { Id = 545, ProvinceId = 36, Name = "SUSUZ" },
            new City { Id = 546, ProvinceId = 58, Name = "SUŞEHRİ" },
            new City { Id = 547, ProvinceId = 61, Name = "SÜRMENE" },
            new City { Id = 548, ProvinceId = 32, Name = "SÜTÇÜLER" },
            new City { Id = 549, ProvinceId = 18, Name = "ŞABANÖZÜ" },
            new City { Id = 550, ProvinceId = 58, Name = "ŞARKIŞLA" },
            new City { Id = 551, ProvinceId = 32, Name = "ŞARKİKARAAĞAÇ" },
            new City { Id = 552, ProvinceId = 59, Name = "ŞARKÖY" },
            new City { Id = 553, ProvinceId = 8, Name = "ŞAVŞAT" },
            new City { Id = 554, ProvinceId = 28, Name = "ŞEBİNKARAHİSAR" },
            new City { Id = 555, ProvinceId = 66, Name = "ŞEFAATLİ" },
            new City { Id = 556, ProvinceId = 30, Name = "ŞEMDİNLİ" },
            new City { Id = 557, ProvinceId = 25, Name = "ŞENKAYA" },
            new City { Id = 558, ProvinceId = 6, Name = "ŞEREFLİKOÇHİSAR" },
            new City { Id = 559, ProvinceId = 34, Name = "ŞİLE" },
            new City { Id = 560, ProvinceId = 29, Name = "ŞİRAN" },
            new City { Id = 561, ProvinceId = 73, Name = "ŞIRNAK MERKEZ" },
            new City { Id = 562, ProvinceId = 56, Name = "ŞİRVAN" },
            new City { Id = 563, ProvinceId = 34, Name = "ŞİŞLİ" },
            new City { Id = 564, ProvinceId = 3, Name = "ŞUHUT" },
            new City { Id = 565, ProvinceId = 33, Name = "TARSUS" },
            new City { Id = 566, ProvinceId = 37, Name = "TAŞKÖPRÜ" },
            new City { Id = 567, ProvinceId = 4, Name = "TAŞLIÇAY" },
            new City { Id = 568, ProvinceId = 5, Name = "TAŞOVA" },
            new City { Id = 569, ProvinceId = 13, Name = "TATVAN" },
            new City { Id = 570, ProvinceId = 20, Name = "TAVAS" },
            new City { Id = 571, ProvinceId = 43, Name = "TAVŞANLI" },
            new City { Id = 572, ProvinceId = 15, Name = "TEFENNİ" },
            new City { Id = 573, ProvinceId = 59, Name = "TEKİRDAĞ MERKEZ" },
            new City { Id = 574, ProvinceId = 25, Name = "TEKMAN" },
            new City { Id = 575, ProvinceId = 24, Name = "TERCAN" },
            new City { Id = 576, ProvinceId = 55, Name = "TERME" },
            new City { Id = 577, ProvinceId = 35, Name = "TİRE" },
            new City { Id = 578, ProvinceId = 28, Name = "TİREBOLU" },
            new City { Id = 579, ProvinceId = 60, Name = "TOKAT MERKEZ" },
            new City { Id = 580, ProvinceId = 38, Name = "TOMARZA" },
            new City { Id = 581, ProvinceId = 61, Name = "TONYA" },
            new City { Id = 582, ProvinceId = 35, Name = "TORBALI" },
            new City { Id = 583, ProvinceId = 25, Name = "TORTUM" },
            new City { Id = 584, ProvinceId = 29, Name = "TORUL" },
            new City { Id = 585, ProvinceId = 37, Name = "TOSYA" },
            new City { Id = 586, ProvinceId = 61, Name = "TRABZON MERKEZ" },
            new City { Id = 587, ProvinceId = 1, Name = "TUFANBEYLİ" },
            new City { Id = 588, ProvinceId = 62, Name = "TUNCELİ MERKEZ" },
            new City { Id = 589, ProvinceId = 45, Name = "TURGUTLU" },
            new City { Id = 590, ProvinceId = 60, Name = "TURHAL" },
            new City { Id = 591, ProvinceId = 4, Name = "TUTAK" },
            new City { Id = 592, ProvinceId = 76, Name = "TUZLUCA" },
            new City { Id = 593, ProvinceId = 57, Name = "TÜRKELİ" },
            new City { Id = 594, ProvinceId = 46, Name = "TÜRKOĞLU" },
            new City { Id = 595, ProvinceId = 48, Name = "ULA" },
            new City { Id = 596, ProvinceId = 52, Name = "ULUBEY" },
            new City { Id = 597, ProvinceId = 64, Name = "ULUBEY" },
            new City { Id = 598, ProvinceId = 73, Name = "ULUDERE" },
            new City { Id = 599, ProvinceId = 32, Name = "ULUBORLU" },
            new City { Id = 600, ProvinceId = 51, Name = "ULUKIŞLA" },
            new City { Id = 601, ProvinceId = 74, Name = "ULUS" },
            new City { Id = 602, ProvinceId = 63, Name = "ŞANLIURFA MERKEZ" },
            new City { Id = 603, ProvinceId = 35, Name = "URLA" },
            new City { Id = 604, ProvinceId = 64, Name = "UŞAK MERKEZ" },
            new City { Id = 605, ProvinceId = 22, Name = "UZUNKÖPRÜ" },
            new City { Id = 606, ProvinceId = 52, Name = "ÜNYE" },
            new City { Id = 607, ProvinceId = 50, Name = "ÜRGÜP" },
            new City { Id = 608, ProvinceId = 34, Name = "ÜSKÜDAR" },
            new City { Id = 609, ProvinceId = 61, Name = "VAKFIKEBİR" },
            new City { Id = 610, ProvinceId = 65, Name = "VAN MERKEZ" },
            new City { Id = 611, ProvinceId = 49, Name = "VARTO" },
            new City { Id = 612, ProvinceId = 55, Name = "VEZİRKÖPRÜ" },
            new City { Id = 613, ProvinceId = 63, Name = "VİRANŞEHİR" },
            new City { Id = 614, ProvinceId = 39, Name = "VİZE" },
            new City { Id = 615, ProvinceId = 38, Name = "YAHYALI" },
            new City { Id = 616, ProvinceId = 77, Name = "YALOVA MERKEZ" },
            new City { Id = 617, ProvinceId = 32, Name = "YALVAÇ" },
            new City { Id = 618, ProvinceId = 18, Name = "YAPRAKLI" },
            new City { Id = 619, ProvinceId = 48, Name = "YATAĞAN" },
            new City { Id = 620, ProvinceId = 27, Name = "YAVUZELİ" },
            new City { Id = 621, ProvinceId = 31, Name = "YAYLADAĞI" },
            new City { Id = 622, ProvinceId = 17, Name = "YENİCE" },
            new City { Id = 623, ProvinceId = 6, Name = "YENİMAHALLE" },
            new City { Id = 624, ProvinceId = 9, Name = "YENİPAZAR" },
            new City { Id = 625, ProvinceId = 16, Name = "YENİŞEHİR" },
            new City { Id = 626, ProvinceId = 66, Name = "YERKÖY" },
            new City { Id = 627, ProvinceId = 38, Name = "YEŞİLHİSAR" },
            new City { Id = 628, ProvinceId = 15, Name = "YEŞİLOVA" },
            new City { Id = 629, ProvinceId = 44, Name = "YEŞİLYURT" },
            new City { Id = 630, ProvinceId = 81, Name = "YIĞILCA" },
            new City { Id = 631, ProvinceId = 58, Name = "YILDIZELİ" },
            new City { Id = 632, ProvinceId = 61, Name = "YOMRA" },
            new City { Id = 633, ProvinceId = 66, Name = "YOZGAT MERKEZ" },
            new City { Id = 634, ProvinceId = 1, Name = "YUMURTALIK" },
            new City { Id = 635, ProvinceId = 42, Name = "YUNAK" },
            new City { Id = 636, ProvinceId = 8, Name = "YUSUFELİ" },
            new City { Id = 637, ProvinceId = 30, Name = "YÜKSEKOVA" },
            new City { Id = 638, ProvinceId = 58, Name = "ZARA" },
            new City { Id = 639, ProvinceId = 34, Name = "ZEYTİNBURNU" },
            new City { Id = 640, ProvinceId = 60, Name = "ZİLE" },
            new City { Id = 641, ProvinceId = 67, Name = "ZONGULDAK MERKEZ" },
            new City { Id = 642, ProvinceId = 48, Name = "DALAMAN" },
            new City { Id = 643, ProvinceId = 80, Name = "DÜZİÇİ" },
            new City { Id = 644, ProvinceId = 6, Name = "GÖLBAŞI" },
            new City { Id = 645, ProvinceId = 6, Name = "KEÇİÖREN" },
            new City { Id = 646, ProvinceId = 6, Name = "MAMAK" },
            new City { Id = 647, ProvinceId = 6, Name = "SİNCAN" },
            new City { Id = 648, ProvinceId = 1, Name = "YÜREĞİR" },
            new City { Id = 649, ProvinceId = 50, Name = "ACIGÖL" },
            new City { Id = 650, ProvinceId = 12, Name = "ADAKLI" },
            new City { Id = 651, ProvinceId = 45, Name = "AHMETLİ" },
            new City { Id = 652, ProvinceId = 38, Name = "AKKIŞLA" },
            new City { Id = 653, ProvinceId = 42, Name = "AKÖREN" },
            new City { Id = 654, ProvinceId = 40, Name = "AKPINAR" },
            new City { Id = 655, ProvinceId = 32, Name = "AKSU" },
            new City { Id = 656, ProvinceId = 36, Name = "AKYAKA" },
            new City { Id = 657, ProvinceId = 1, Name = "ALADAĞ" },
            new City { Id = 658, ProvinceId = 67, Name = "ALAPLI" },
            new City { Id = 659, ProvinceId = 26, Name = "ALPU" },
            new City { Id = 660, ProvinceId = 42, Name = "ALTINEKİN" },
            new City { Id = 661, ProvinceId = 74, Name = "AMASRA" },
            new City { Id = 662, ProvinceId = 23, Name = "ARICAK" },
            new City { Id = 663, ProvinceId = 55, Name = "ASARCIK" },
            new City { Id = 664, ProvinceId = 43, Name = "ASLANAPA" },
            new City { Id = 665, ProvinceId = 18, Name = "ATKARACALAR" },
            new City { Id = 666, ProvinceId = 33, Name = "AYDINCIK" },
            new City { Id = 667, ProvinceId = 69, Name = "AYDINTEPE" },
            new City { Id = 668, ProvinceId = 70, Name = "AYRANCI" },
            new City { Id = 669, ProvinceId = 20, Name = "BABADAĞ" },
            new City { Id = 670, ProvinceId = 65, Name = "BAHÇESARAY" },
            new City { Id = 671, ProvinceId = 3, Name = "BAŞMAKÇI" },
            new City { Id = 672, ProvinceId = 44, Name = "BATTALGAZİ" },
            new City { Id = 673, ProvinceId = 3, Name = "BAYAT" },
            new City { Id = 674, ProvinceId = 20, Name = "BEKİLLİ" },
            new City { Id = 675, ProvinceId = 61, Name = "BEŞİKDÜZÜ" },
            new City { Id = 676, ProvinceId = 35, Name = "BEYDAĞ" },
            new City { Id = 677, ProvinceId = 26, Name = "BEYLİKOVA" },
            new City { Id = 678, ProvinceId = 19, Name = "BOĞAZKALE" },
            new City { Id = 679, ProvinceId = 33, Name = "BOZYAZI" },
            new City { Id = 680, ProvinceId = 35, Name = "BUCA" },
            new City { Id = 681, ProvinceId = 9, Name = "BUHARKENT" },
            new City { Id = 682, ProvinceId = 34, Name = "BÜYÜKÇEKMECE" },
            new City { Id = 683, ProvinceId = 16, Name = "BÜYÜKORHAN" },
            new City { Id = 684, ProvinceId = 81, Name = "CUMAYERİ" },
            new City { Id = 685, ProvinceId = 46, Name = "ÇAĞLIYANCERİT" },
            new City { Id = 686, ProvinceId = 65, Name = "ÇALDIRAN" },
            new City { Id = 687, ProvinceId = 47, Name = "DARGEÇİT" },
            new City { Id = 688, ProvinceId = 69, Name = "DEMİRÖZÜ" },
            new City { Id = 689, ProvinceId = 42, Name = "DEREBUCAK" },
            new City { Id = 690, ProvinceId = 43, Name = "DUMLUPINAR" },
            new City { Id = 691, ProvinceId = 21, Name = "EĞİL" },
            new City { Id = 692, ProvinceId = 31, Name = "ERZİN" },
            new City { Id = 693, ProvinceId = 45, Name = "GÖLMARMARA" },
            new City { Id = 694, ProvinceId = 81, Name = "GÖLYAKA" },
            new City { Id = 695, ProvinceId = 52, Name = "GÜLYALI" },
            new City { Id = 696, ProvinceId = 53, Name = "GÜNEYSU" },
            new City { Id = 697, ProvinceId = 52, Name = "GÜRGENTEPE" },
            new City { Id = 698, ProvinceId = 13, Name = "GÜROYMAK" },
            new City { Id = 699, ProvinceId = 16, Name = "HARMANCIK" },
            new City { Id = 700, ProvinceId = 63, Name = "HARRAN" },
            new City { Id = 701, ProvinceId = 49, Name = "HASKÖY" },
            new City { Id = 702, ProvinceId = 43, Name = "HİSARCIK" },
            new City { Id = 703, ProvinceId = 20, Name = "HONAZ" },
            new City { Id = 704, ProvinceId = 42, Name = "HÜYÜK" },
            new City { Id = 705, ProvinceId = 37, Name = "İHSANGAZİ" },
            new City { Id = 706, ProvinceId = 1, Name = "İMAMOĞLU" },
            new City { Id = 707, ProvinceId = 9, Name = "İNCİRLİOVA" },
            new City { Id = 708, ProvinceId = 26, Name = "İNÖNÜ" },
            new City { Id = 709, ProvinceId = 3, Name = "İSCEHİSAR" },
            new City { Id = 710, ProvinceId = 34, Name = "KAĞITHANE" },
            new City { Id = 711, ProvinceId = 7, Name = "KALE" },
            new City { Id = 712, ProvinceId = 25, Name = "KARAÇOBAN" },
            new City { Id = 713, ProvinceId = 15, Name = "KARAMANLI" },
            new City { Id = 714, ProvinceId = 42, Name = "KARATAY" },
            new City { Id = 715, ProvinceId = 6, Name = "KAZAN" },
            new City { Id = 716, ProvinceId = 15, Name = "KEMER" },
            new City { Id = 717, ProvinceId = 18, Name = "KIZILIRMAK" },
            new City { Id = 718, ProvinceId = 54, Name = "KOCAALİ" },
            new City { Id = 719, ProvinceId = 35, Name = "KONAK" },
            new City { Id = 720, ProvinceId = 23, Name = "KOVANCILAR" },
            new City { Id = 721, ProvinceId = 41, Name = "KÖRFEZ" },
            new City { Id = 722, ProvinceId = 29, Name = "KÖSE" },
            new City { Id = 723, ProvinceId = 34, Name = "KÜÇÜKÇEKMECE" },
            new City { Id = 724, ProvinceId = 10, Name = "MARMARA" },
            new City { Id = 725, ProvinceId = 59, Name = "MARMARAEREĞLİSİ" },
            new City { Id = 726, ProvinceId = 35, Name = "MENDERES" },
            new City { Id = 727, ProvinceId = 42, Name = "MERAM" },
            new City { Id = 728, ProvinceId = 8, Name = "MURGUL" },
            new City { Id = 729, ProvinceId = 16, Name = "NİLÜFER" },
            new City { Id = 730, ProvinceId = 55, Name = "ONDOKUZMAYIS" },
            new City { Id = 731, ProvinceId = 48, Name = "ORTACA" },
            new City { Id = 732, ProvinceId = 16, Name = "OSMANGAZİ" },
            new City { Id = 733, ProvinceId = 54, Name = "PAMUKOVA" },
            new City { Id = 734, ProvinceId = 60, Name = "PAZAR" },
            new City { Id = 735, ProvinceId = 34, Name = "PENDİK" },
            new City { Id = 736, ProvinceId = 37, Name = "PINARBAŞI" },
            new City { Id = 737, ProvinceId = 28, Name = "PİRAZİZ" },
            new City { Id = 738, ProvinceId = 55, Name = "SALIPAZARI" },
            new City { Id = 739, ProvinceId = 42, Name = "SELÇUKLU" },
            new City { Id = 740, ProvinceId = 20, Name = "SERİNHİSAR" },
            new City { Id = 741, ProvinceId = 27, Name = "ŞAHİNBEY" },
            new City { Id = 742, ProvinceId = 61, Name = "ŞALPAZARI" },
            new City { Id = 743, ProvinceId = 43, Name = "ŞAPHANE" },
            new City { Id = 744, ProvinceId = 27, Name = "ŞEHİTKAMİL" },
            new City { Id = 745, ProvinceId = 37, Name = "ŞENPAZAR" },
            new City { Id = 746, ProvinceId = 38, Name = "TALAS" },
            new City { Id = 747, ProvinceId = 54, Name = "TARAKLI" },
            new City { Id = 748, ProvinceId = 42, Name = "TAŞKENT" },
            new City { Id = 749, ProvinceId = 55, Name = "TEKKEKÖY" },
            new City { Id = 750, ProvinceId = 19, Name = "UĞURLUDAĞ" },
            new City { Id = 751, ProvinceId = 25, Name = "UZUNDERE" },
            new City { Id = 752, ProvinceId = 34, Name = "ÜMRANİYE" },
            new City { Id = 753, ProvinceId = 24, Name = "ÜZÜMLÜ" },
            new City { Id = 754, ProvinceId = 28, Name = "YAĞLIDERE" },
            new City { Id = 755, ProvinceId = 12, Name = "YAYLADERE" },
            new City { Id = 756, ProvinceId = 78, Name = "YENİCE" },
            new City { Id = 757, ProvinceId = 11, Name = "YENİPAZAR" },
            new City { Id = 758, ProvinceId = 60, Name = "YEŞİLYURT" },
            new City { Id = 759, ProvinceId = 16, Name = "YILDIRIM" },
            new City { Id = 760, ProvinceId = 68, Name = "AĞAÇÖREN" },
            new City { Id = 761, ProvinceId = 68, Name = "GÜZELYURT" },
            new City { Id = 762, ProvinceId = 70, Name = "KÂZIMKARABEKİR" },
            new City { Id = 763, ProvinceId = 38, Name = "KOCASİNAN" },
            new City { Id = 764, ProvinceId = 38, Name = "MELİKGAZİ" },
            new City { Id = 765, ProvinceId = 25, Name = "PAZARYOLU" },
            new City { Id = 766, ProvinceId = 68, Name = "SARIYAHŞİ" },
            new City { Id = 767, ProvinceId = 37, Name = "AĞLI" },
            new City { Id = 768, ProvinceId = 42, Name = "AHIRLI" },
            new City { Id = 769, ProvinceId = 40, Name = "AKÇAKENT" },
            new City { Id = 770, ProvinceId = 58, Name = "AKINCILAR" },
            new City { Id = 771, ProvinceId = 20, Name = "AKKÖY" },
            new City { Id = 772, ProvinceId = 6, Name = "AKYURT" },
            new City { Id = 773, ProvinceId = 23, Name = "ALACAKAYA" },
            new City { Id = 774, ProvinceId = 15, Name = "ALTINYAYLA" },
            new City { Id = 775, ProvinceId = 58, Name = "ALTINYAYLA" },
            new City { Id = 776, ProvinceId = 51, Name = "ALTUNHİSAR" },
            new City { Id = 777, ProvinceId = 66, Name = "AYDINCIK" },
            new City { Id = 778, ProvinceId = 56, Name = "AYDINLAR" },
            new City { Id = 779, ProvinceId = 55, Name = "AYVACIK" },
            new City { Id = 780, ProvinceId = 71, Name = "BAHŞİLİ" },
            new City { Id = 781, ProvinceId = 20, Name = "BAKLAN" },
            new City { Id = 782, ProvinceId = 71, Name = "BALIŞEYH" },
            new City { Id = 783, ProvinceId = 60, Name = "BAŞÇİFTLİK" },
            new City { Id = 784, ProvinceId = 70, Name = "BAŞYAYLA" },
            new City { Id = 785, ProvinceId = 18, Name = "BAYRAMÖREN" },
            new City { Id = 786, ProvinceId = 34, Name = "BAYRAMPAŞA" },
            new City { Id = 787, ProvinceId = 31, Name = "BELEN" },
            new City { Id = 788, ProvinceId = 20, Name = "BEYAĞAÇ" },
            new City { Id = 789, ProvinceId = 20, Name = "BOZKURT" },
            new City { Id = 790, ProvinceId = 40, Name = "BOZTEPE" },
            new City { Id = 791, ProvinceId = 52, Name = "ÇAMAŞ" },
            new City { Id = 792, ProvinceId = 33, Name = "ÇAMLIYAYLA" },
            new City { Id = 793, ProvinceId = 28, Name = "ÇAMOLUK" },
            new City { Id = 794, ProvinceId = 28, Name = "ÇANAKÇI" },
            new City { Id = 795, ProvinceId = 66, Name = "ÇANDIR" },
            new City { Id = 796, ProvinceId = 61, Name = "ÇARŞIBAŞI" },
            new City { Id = 797, ProvinceId = 52, Name = "ÇATALPINAR" },
            new City { Id = 798, ProvinceId = 43, Name = "ÇAVDARHİSAR" },
            new City { Id = 799, ProvinceId = 15, Name = "ÇAVDIR" },
            new City { Id = 800, ProvinceId = 52, Name = "ÇAYBAŞI" },
            new City { Id = 801, ProvinceId = 71, Name = "ÇELEBİ" },
            new City { Id = 802, ProvinceId = 42, Name = "ÇELTİK" },
            new City { Id = 803, ProvinceId = 15, Name = "ÇELTİKÇİ" },
            new City { Id = 804, ProvinceId = 51, Name = "ÇİFTLİK" },
            new City { Id = 805, ProvinceId = 81, Name = "ÇİLİMLİ" },
            new City { Id = 806, ProvinceId = 3, Name = "ÇOBANLAR" },
            new City { Id = 807, ProvinceId = 42, Name = "DERBENT" },
            new City { Id = 808, ProvinceId = 53, Name = "DEREPAZARI" },
            new City { Id = 809, ProvinceId = 61, Name = "DERNEKPAZARI" },
            new City { Id = 810, ProvinceId = 57, Name = "DİKMEN" },
            new City { Id = 811, ProvinceId = 19, Name = "DODURGA" },
            new City { Id = 812, ProvinceId = 28, Name = "DOĞANKENT" },
            new City { Id = 813, ProvinceId = 58, Name = "DOĞANŞAR" },
            new City { Id = 814, ProvinceId = 44, Name = "DOĞANYOL" },
            new City { Id = 815, ProvinceId = 37, Name = "DOĞANYURT" },
            new City { Id = 816, ProvinceId = 14, Name = "DÖRTDİVAN" },
            new City { Id = 817, ProvinceId = 61, Name = "DÜZKÖY" },
            new City { Id = 818, ProvinceId = 65, Name = "EDREMİT" },
            new City { Id = 819, ProvinceId = 46, Name = "EKİNÖZÜ" },
            new City { Id = 820, ProvinceId = 42, Name = "EMİRGAZİ" },
            new City { Id = 821, ProvinceId = 68, Name = "ESKİL" },
            new City { Id = 822, ProvinceId = 6, Name = "ETİMESGUT" },
            new City { Id = 823, ProvinceId = 3, Name = "EVCİLER" },
            new City { Id = 824, ProvinceId = 6, Name = "EVREN" },
            new City { Id = 825, ProvinceId = 54, Name = "FERİZLİ" },
            new City { Id = 826, ProvinceId = 67, Name = "GÖKÇEBEY" },
            new City { Id = 827, ProvinceId = 58, Name = "GÖLOVA" },
            new City { Id = 828, ProvinceId = 10, Name = "GÖMEÇ" },
            new City { Id = 829, ProvinceId = 32, Name = "GÖNEN" },
            new City { Id = 830, ProvinceId = 28, Name = "GÜCE" },
            new City { Id = 831, ProvinceId = 73, Name = "GÜÇLÜKONAK" },
            new City { Id = 832, ProvinceId = 68, Name = "GÜLAĞAÇ" },
            new City { Id = 833, ProvinceId = 42, Name = "GÜNEYSINIR" },
            new City { Id = 834, ProvinceId = 26, Name = "GÜNYÜZÜ" },
            new City { Id = 835, ProvinceId = 16, Name = "GÜRSU" },
            new City { Id = 836, ProvinceId = 38, Name = "HACILAR" },
            new City { Id = 837, ProvinceId = 42, Name = "HALKAPINAR" },
            new City { Id = 838, ProvinceId = 5, Name = "HAMAMÖZÜ" },
            new City { Id = 839, ProvinceId = 26, Name = "HAN" },
            new City { Id = 840, ProvinceId = 37, Name = "HANÖNÜ" },
            new City { Id = 841, ProvinceId = 72, Name = "HASANKEYF" },
            new City { Id = 842, ProvinceId = 61, Name = "HAYRAT" },
            new City { Id = 843, ProvinceId = 53, Name = "HEMŞİN" },
            new City { Id = 844, ProvinceId = 3, Name = "HOCALAR" },
            new City { Id = 845, ProvinceId = 25, Name = "ILICA" },
            new City { Id = 846, ProvinceId = 7, Name = "İBRADI" },
            new City { Id = 847, ProvinceId = 52, Name = "İKİZCE" },
            new City { Id = 848, ProvinceId = 11, Name = "İNHİSAR" },
            new City { Id = 849, ProvinceId = 53, Name = "İYİDERE" },
            new City { Id = 850, ProvinceId = 52, Name = "KABADÜZ" },
            new City { Id = 851, ProvinceId = 52, Name = "KABATAŞ" },
            new City { Id = 852, ProvinceId = 66, Name = "KADIŞEHRİ" },
            new City { Id = 853, ProvinceId = 44, Name = "KALE" },
            new City { Id = 854, ProvinceId = 71, Name = "KARAKEÇİLİ" },
            new City { Id = 855, ProvinceId = 54, Name = "KARAPÜRÇEK" },
            new City { Id = 856, ProvinceId = 27, Name = "KARKAMIŞ" },
            new City { Id = 857, ProvinceId = 9, Name = "KARPUZLU" },
            new City { Id = 858, ProvinceId = 48, Name = "KAVAKLIDERE" },
            new City { Id = 859, ProvinceId = 7, Name = "KEMER" },
            new City { Id = 860, ProvinceId = 16, Name = "KESTEL" },
            new City { Id = 861, ProvinceId = 3, Name = "KIZILÖREN" },
            new City { Id = 862, ProvinceId = 21, Name = "KOCAKÖY" },
            new City { Id = 863, ProvinceId = 18, Name = "KORGUN" },
            new City { Id = 864, ProvinceId = 49, Name = "KORKUT" },
            new City { Id = 865, ProvinceId = 45, Name = "KÖPRÜBAŞI" },
            new City { Id = 866, ProvinceId = 61, Name = "KÖPRÜBAŞI" },
            new City { Id = 867, ProvinceId = 25, Name = "KÖPRÜKÖY" },
            new City { Id = 868, ProvinceId = 9, Name = "KÖŞK" },
            new City { Id = 869, ProvinceId = 44, Name = "KULUNCAK" },
            new City { Id = 870, ProvinceId = 31, Name = "KUMLU" },
            new City { Id = 871, ProvinceId = 29, Name = "KÜRTÜN" },
            new City { Id = 872, ProvinceId = 19, Name = "LAÇİN" },
            new City { Id = 873, ProvinceId = 26, Name = "MİHALGAZİ" },
            new City { Id = 874, ProvinceId = 27, Name = "NURDAĞI" },
            new City { Id = 875, ProvinceId = 46, Name = "NURHAK" },
            new City { Id = 876, ProvinceId = 19, Name = "OĞUZLAR" },
            new City { Id = 877, ProvinceId = 24, Name = "OTLUKBELİ" },
            new City { Id = 878, ProvinceId = 38, Name = "ÖZVATAN" },
            new City { Id = 879, ProvinceId = 43, Name = "PAZARLAR" },
            new City { Id = 880, ProvinceId = 65, Name = "SARAY" },
            new City { Id = 881, ProvinceId = 57, Name = "SARAYDÜZÜ" },
            new City { Id = 882, ProvinceId = 66, Name = "SARAYKENT" },
            new City { Id = 883, ProvinceId = 70, Name = "SARIVELİLER" },
            new City { Id = 884, ProvinceId = 37, Name = "SEYDİLER" },
            new City { Id = 885, ProvinceId = 2, Name = "SİNCİK" },
            new City { Id = 886, ProvinceId = 54, Name = "SÖĞÜTLÜ" },
            new City { Id = 887, ProvinceId = 60, Name = "SULUSARAY" },
            new City { Id = 888, ProvinceId = 22, Name = "SÜLOĞLU" },
            new City { Id = 889, ProvinceId = 2, Name = "TUT" },
            new City { Id = 890, ProvinceId = 42, Name = "TUZLUKÇU" },
            new City { Id = 891, ProvinceId = 58, Name = "ULAŞ" },
            new City { Id = 892, ProvinceId = 71, Name = "YAHŞİHAN" },
            new City { Id = 893, ProvinceId = 55, Name = "YAKAKENT" },
            new City { Id = 894, ProvinceId = 42, Name = "YALIHÜYÜK" },
            new City { Id = 895, ProvinceId = 44, Name = "YAZIHAN" },
            new City { Id = 896, ProvinceId = 12, Name = "YEDİSU" },
            new City { Id = 897, ProvinceId = 14, Name = "YENİÇAĞA" },
            new City { Id = 898, ProvinceId = 66, Name = "YENİFAKILI" },
            new City { Id = 899, ProvinceId = 9, Name = "DİDİM (YENİHİSAR)" },
            new City { Id = 900, ProvinceId = 32, Name = "YENİŞARBADEMLİ" },
            new City { Id = 901, ProvinceId = 47, Name = "YEŞİLLİ" },
            new City { Id = 902, ProvinceId = 34, Name = "AVCILAR" },
            new City { Id = 903, ProvinceId = 34, Name = "BAĞCILAR" },
            new City { Id = 904, ProvinceId = 34, Name = "BAHÇELİEVLER" },
            new City { Id = 905, ProvinceId = 35, Name = "BALÇOVA" },
            new City { Id = 906, ProvinceId = 35, Name = "ÇİĞLİ" },
            new City { Id = 907, ProvinceId = 75, Name = "DAMAL" },
            new City { Id = 908, ProvinceId = 35, Name = "GAZİEMİR" },
            new City { Id = 909, ProvinceId = 34, Name = "GÜNGÖREN" },
            new City { Id = 910, ProvinceId = 76, Name = "KARAKOYUNLU" },
            new City { Id = 911, ProvinceId = 34, Name = "MALTEPE" },
            new City { Id = 912, ProvinceId = 35, Name = "NARLIDERE" },
            new City { Id = 913, ProvinceId = 34, Name = "SULTANBEYLİ" },
            new City { Id = 914, ProvinceId = 34, Name = "TUZLA" },
            new City { Id = 915, ProvinceId = 34, Name = "ESENLER" },
            new City { Id = 916, ProvinceId = 81, Name = "GÜMÜŞOVA" },
            new City { Id = 917, ProvinceId = 35, Name = "GÜZELBAHÇE" },
            new City { Id = 918, ProvinceId = 77, Name = "ALTINOVA" },
            new City { Id = 919, ProvinceId = 77, Name = "ARMUTLU" },
            new City { Id = 920, ProvinceId = 77, Name = "ÇINARCIK" },
            new City { Id = 921, ProvinceId = 77, Name = "ÇİFTLİKKÖY" },
            new City { Id = 922, ProvinceId = 79, Name = "ELBEYLİ" },
            new City { Id = 923, ProvinceId = 79, Name = "MUSABEYLİ" },
            new City { Id = 924, ProvinceId = 79, Name = "POLATELİ" },
            new City { Id = 925, ProvinceId = 77, Name = "TERMAL" },
            new City { Id = 926, ProvinceId = 80, Name = "HASANBEYLİ" },
            new City { Id = 927, ProvinceId = 80, Name = "SUMBAS" },
            new City { Id = 928, ProvinceId = 80, Name = "TOPRAKKALE" },
            new City { Id = 929, ProvinceId = 41, Name = "DERİNCE" },
            new City { Id = 930, ProvinceId = 81, Name = "KAYNAŞLI" },
            new City { Id = 931, ProvinceId = 1, Name = "SARIÇAM" },
            new City { Id = 932, ProvinceId = 1, Name = "ÇUKUROVA" },
            new City { Id = 933, ProvinceId = 6, Name = "PURSAKLAR" },
            new City { Id = 934, ProvinceId = 7, Name = "AKSU/ANTALYA" },
            new City { Id = 935, ProvinceId = 7, Name = "DÖŞEMEALTI" },
            new City { Id = 936, ProvinceId = 7, Name = "KEPEZ" },
            new City { Id = 937, ProvinceId = 7, Name = "KONYAALTI" },
            new City { Id = 938, ProvinceId = 7, Name = "MURATPAŞA" },
            new City { Id = 939, ProvinceId = 21, Name = "BAĞLAR" },
            new City { Id = 940, ProvinceId = 21, Name = "KAYAPINAR" },
            new City { Id = 941, ProvinceId = 21, Name = "SUR" },
            new City { Id = 942, ProvinceId = 21, Name = "YENİŞEHİR/DİYARBAKIR" },
            new City { Id = 943, ProvinceId = 25, Name = "PALANDÖKEN" },
            new City { Id = 944, ProvinceId = 25, Name = "YAKUTİYE" },
            new City { Id = 945, ProvinceId = 26, Name = "ODUNPAZARI" },
            new City { Id = 946, ProvinceId = 26, Name = "TEPEBAŞI" },
            new City { Id = 947, ProvinceId = 34, Name = "ARNAVUTKÖY" },
            new City { Id = 948, ProvinceId = 34, Name = "ATAŞEHİR" },
            new City { Id = 949, ProvinceId = 34, Name = "BAŞAKŞEHİR" },
            new City { Id = 950, ProvinceId = 34, Name = "BEYLİKDÜZÜ" },
            new City { Id = 951, ProvinceId = 34, Name = "ÇEKMEKÖY" },
            new City { Id = 952, ProvinceId = 34, Name = "ESENYURT" },
            new City { Id = 953, ProvinceId = 34, Name = "SANCAKTEPE" },
            new City { Id = 954, ProvinceId = 34, Name = "SULTANGAZİ" },
            new City { Id = 955, ProvinceId = 35, Name = "BAYRAKLI" },
            new City { Id = 956, ProvinceId = 35, Name = "KARABAĞLAR" },
            new City { Id = 957, ProvinceId = 41, Name = "BAŞİSKELE" },
            new City { Id = 958, ProvinceId = 41, Name = "ÇAYIROVA" },
            new City { Id = 959, ProvinceId = 41, Name = "DARICA " },
            new City { Id = 960, ProvinceId = 41, Name = "DİLOVASI" },
            new City { Id = 961, ProvinceId = 41, Name = "İZMİT" },
            new City { Id = 962, ProvinceId = 41, Name = "KARTEPE" },
            new City { Id = 963, ProvinceId = 33, Name = "AKDENİZ" },
            new City { Id = 964, ProvinceId = 33, Name = "MEZİTLİ" },
            new City { Id = 965, ProvinceId = 33, Name = "TOROSLAR" },
            new City { Id = 966, ProvinceId = 33, Name = "YENİŞEHİR/MERSİN" },
            new City { Id = 967, ProvinceId = 54, Name = "ADAPAZARI" },
            new City { Id = 968, ProvinceId = 54, Name = "ARİFİYE" },
            new City { Id = 969, ProvinceId = 54, Name = "ERENLER" },
            new City { Id = 970, ProvinceId = 54, Name = "SERDİVAN" },
            new City { Id = 971, ProvinceId = 55, Name = "ATAKUM" },
            new City { Id = 972, ProvinceId = 55, Name = "CANİK" },
            new City { Id = 973, ProvinceId = 55, Name = "İLKADIM" }

        );
    }
}
